package br.com.sge.view;

import br.com.sge.model.UsuarioModel;
import br.com.sge.service.UsuarioService;
import br.com.sge.util.alerts.AWTUtilities;
import br.com.sge.util.alerts.ErrorAlert;
import br.com.sge.util.alerts.SuccessAlert;
import static br.com.sge.view.Users.jtUsers;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joseluiz
 */
public class NewUser extends javax.swing.JDialog {

    UsuarioService usuarioService = new UsuarioService();
    UsuarioModel usuarioModel = new UsuarioModel();
    ArrayList<UsuarioModel> listaUsuarioModel = new ArrayList<>();
    public String login, password, tipo, nome;
    Timer timer = null;
    TimerTask task;
    int i = 32;

    /**
     * Creates new form ModalProducto
     *
     * @param parent
     * @param modal
     */
    public NewUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AWTUtilities.setOpaque(this, false);
        this.jcbTipo.setCursor(new Cursor(12));
        NewUser.nombreUs.setVisible(false);
        localization(0);
        this.jtfName.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        titulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfLogin = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfPassword = new jpass.JRPasswordField();
        jLabel8 = new javax.swing.JLabel();
        nombreUs = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jtfName = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbClean = new principal.MaterialButton();
        jbRegister = new principal.MaterialButton();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sge/images/alerts/fondo.png"))); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(58, 159, 171));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("NOVO USUÁRIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 458, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel4.setBorder(dropShadowBorder1);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sge/images/icon/icono-usuario.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 50, -1));

        jtfLogin.setBorder(null);
        jtfLogin.setForeground(new java.awt.Color(58, 159, 171));
        jtfLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfLogin.setPlaceholder("LOGIN");
        jtfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLoginActionPerformed(evt);
            }
        });
        jPanel4.add(jtfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 240, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sge/images/icon/campo-usuario.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jtfPassword.setBorder(null);
        jtfPassword.setForeground(new java.awt.Color(58, 159, 171));
        jtfPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfPassword.setPlaceholder("SENHA");
        jtfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPasswordActionPerformed(evt);
            }
        });
        jPanel4.add(jtfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 240, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sge/images/icon/campo-contrasena.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        nombreUs.setText("NSOFT");
        jPanel4.add(nombreUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 370, -1));

        jcbTipo.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        jcbTipo.setForeground(new java.awt.Color(0, 0, 0));
        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE USUÁRIO", "ADMINISTRADOR", "CONVIDADO", "NORMAL" }));
        jcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoActionPerformed(evt);
            }
        });
        jPanel4.add(jcbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 260, 30));

        jtfName.setBorder(null);
        jtfName.setForeground(new java.awt.Color(58, 159, 171));
        jtfName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfName.setPlaceholder("NOME");
        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });
        jPanel4.add(jtfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 240, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sge/images/icon/campo-usuario.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        panel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 420, 330));

        jPanel3.setBackground(new java.awt.Color(58, 159, 171));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbClean.setBackground(new java.awt.Color(255, 255, 255));
        jbClean.setForeground(new java.awt.Color(58, 159, 171));
        jbClean.setText("LIMPAR CAMPOS");
        jbClean.setToolTipText("");
        jbClean.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbClean.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jbClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCleanActionPerformed(evt);
            }
        });
        jPanel3.add(jbClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 160, 50));

        jbRegister.setBackground(new java.awt.Color(255, 255, 255));
        jbRegister.setForeground(new java.awt.Color(58, 159, 171));
        jbRegister.setText("REGISTRAR");
        jbRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbRegister.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jbRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegisterActionPerformed(evt);
            }
        });
        jbRegister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jbRegisterKeyTyped(evt);
            }
        });
        jPanel3.add(jbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 50));

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("id");
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 30, -1));

        panel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 340, 459, 170));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 476, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        task = new TimerTask() {
            @Override
            public void run() {
                if (i == 0) {
                    close();
                } else {
                    localization(i);
                    i -= 32;
                    Trasparencia((float) i / 352);
                }
            }
        };
        timer = new Timer();
        timer.schedule(task, 0, 2);
    }//GEN-LAST:event_cerrarActionPerformed

    private void jbCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCleanActionPerformed
        cleanFields();
    }//GEN-LAST:event_jbCleanActionPerformed

    private void jbRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegisterActionPerformed

        login = jtfLogin.getText();
        password = jtfPassword.getText();
        if (jbRegister.getText().equals("REGISTRAR")) {
            registerNewUser();
        } else {
            modifyUsers();
        }

    }//GEN-LAST:event_jbRegisterActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        task = new TimerTask() {
            @Override
            public void run() {
                if (i == 352) {
                    timer.cancel();
                } else {
                    localization(i);
                    i += 32;
                    Trasparencia((float) i / 352);
                }
            }
        };
        timer = new Timer();
        timer.schedule(task, 0, 2);
    }//GEN-LAST:event_formWindowOpened

    private void jbRegisterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbRegisterKeyTyped
        if ((evt.getKeyChar() == KeyEvent.VK_ENTER)) {
            registerNewUser();
        }
    }//GEN-LAST:event_jbRegisterKeyTyped

    private void jtfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLoginActionPerformed
        jtfPassword.requestFocusInWindow();
    }//GEN-LAST:event_jtfLoginActionPerformed

    private void jtfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPasswordActionPerformed
        jcbTipo.requestFocusInWindow();
        jcbTipo.showPopup();
    }//GEN-LAST:event_jtfPasswordActionPerformed

    private void jcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoActionPerformed
        //  jbRegister.requestFocusInWindow();
    }//GEN-LAST:event_jcbTipoActionPerformed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameActionPerformed

    private void registerNewUser() {
        if (login.equals("") || login.equals("")
                || this.jcbTipo.getSelectedIndex() == 0) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            ErrorAlert.titulo.setText("AVISO!!");
            ErrorAlert.msj.setText("HÁ CAMPOS EM BRANCO");
            ErrorAlert.msj1.setText("");
            er.setVisible(true);

        } else {
            usuarioModel.setUsuLogin(jtfLogin.getText());
            usuarioModel.setUsuNome(jtfLogin.getText().toUpperCase());
            usuarioModel.setUsuSenha(String.valueOf(jtfPassword.getPassword()));
            usuarioModel.setUsuTipo(jcbTipo.getSelectedItem().toString());
            try {
                if (usuarioService.salvarUsuarioDAO(usuarioModel) > 0) {
                    SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                    SuccessAlert.titulo.setText("SUCESSO!!");
                    SuccessAlert.msj.setText("FOI REGISTRADO UM ");
                    SuccessAlert.msj1.setText("NOVO USUÁRIO");
                    sa.setVisible(true);
                    loadUsers();
                    cleanFields();
                }
            } catch (HeadlessException e) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                ErrorAlert.titulo.setText("AVISO!!");
                ErrorAlert.msj.setText("O REGISTRO DO NOVO USUÁRIO");
                ErrorAlert.msj1.setText("NÃO FOI SALVO!");
                er.setVisible(true);
            }
        }
    }

    private void loadUsers() {
        /**
         * Array que buscará no BD (atraves do Controller) os dados para serem
         * exibidos na tabela
         */
        listaUsuarioModel = usuarioService.getListaUsuarioDAO();
        DefaultTableModel modelo = (DefaultTableModel) jtUsers.getModel(); //populando a tabela na janela de usuários

        // Setando a quantidade de linhas que a tabela para não haver duplicação de
        // dados
        modelo.setNumRows(0);

        try {
            /**
             * insere os produtos na tabela
             */
            int cont = listaUsuarioModel.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(
                        new Object[]{listaUsuarioModel.get(i).getIdUsuario(),
                            listaUsuarioModel.get(i).getUsuNome(),
                            listaUsuarioModel.get(i).getUsuLogin(),
                            listaUsuarioModel.get(i).getUsuSenha(),
                            listaUsuarioModel.get(i).getUsuTipo()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar usuários para preencher a tabela\n" + e.toString());

        }
    }

    private void cleanFields() {
        this.jtfName.setText("");
        this.jtfName.requestFocus();
        NewUser.jtfLogin.setText("");
        NewUser.jtfPassword.setText("");
        this.jcbTipo.setSelectedIndex(0);
    }

    public void loadDataUser() {
        jtfLogin.setText(login);
        jtfPassword.setText(password);
        jtfName.setText(nome);
    }

    public void modifyUsers() {
        usuarioModel.setIdUsuario(Integer.parseInt(id.getText()));
        usuarioModel.setUsuLogin(jtfLogin.getText());
        usuarioModel.setUsuNome(jtfLogin.getText().toUpperCase());
        usuarioModel.setUsuSenha(String.valueOf(jtfPassword.getPassword()));
        usuarioModel.setUsuTipo(jcbTipo.getSelectedItem().toString());
        if (usuarioService.atualizarUsuarioDAO(usuarioModel)) {
            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
            SuccessAlert.titulo.setText("SUCESSO!!");
            SuccessAlert.msj.setText("O USUÁRIO FOI ALTERADO ");
            SuccessAlert.msj1.setText("COM SUCESSO!");
            sa.setVisible(true);
            loadUsers();
            cleanFields();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar o usuário!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton cerrar;
    public static javax.swing.JLabel id;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private principal.MaterialButton jbClean;
    public principal.MaterialButton jbRegister;
    public javax.swing.JComboBox<String> jcbTipo;
    public static app.bolivia.swing.JCTextField jtfLogin;
    private app.bolivia.swing.JCTextField jtfName;
    public static jpass.JRPasswordField jtfPassword;
    public static javax.swing.JLabel nombreUs;
    private org.edisoncor.gui.panel.Panel panel1;
    public static javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    private void close() {
        this.dispose();
        timer = null;
        task = null;
    }

    private void Trasparencia(float trasp) {
        AWTUtilities.setOpacity(this, trasp);
    }

    private void localization(int y) {
        this.setLocation(603, y - 200);
    }
}
